run:
  timeout: 5m
  
linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - errcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/QRY91/uroboro

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 